# This file was generated by GoReleaser. DO NOT EDIT.
cask "things" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "caffcf78d3b5f895177f982cf95fccf35b37d9a1cc164bbf69d2920aa6fb19f6"
      url "https://github.com/ryanlewis/things-cli/releases/download/v#{version}/things_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "27da3ec766510e8f2f09c883da47f9978477449382c9d820d6845b3bf5b0ab2a"
      url "https://github.com/ryanlewis/things-cli/releases/download/v#{version}/things_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "things"
  desc "Manage your Things3 to-dos from the terminal."
  homepage "https://github.com/ryanlewis/things-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "things"

  generate_completions_from_executable "things", "completions",
    base_name: "things",
    shells: [:bash, :zsh, :fish]

  zap trash: [
      "~/Library/Caches/things-cli",
    ]

end
