# This file was generated by GoReleaser. DO NOT EDIT.
cask "things" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "4f5b658ebca9dad6bf08e61e0df515230d573b5e777312eed9868928e5631094"
      url "https://github.com/ryanlewis/things-cli/releases/download/v#{version}/things_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ryanlewis/things-cli/"
    end
    on_intel do
      sha256 "90d48bc0d7c62b3ca1a1341f35609145e58c052b6daacbc278f895e307982193"
      url "https://github.com/ryanlewis/things-cli/releases/download/v#{version}/things_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ryanlewis/things-cli/"
    end
  end

  name "things"
  desc "Manage your Things3 to-dos from the terminal."
  homepage "https://github.com/ryanlewis/things-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "things"

  generate_completions_from_executable "things", "completions",
    base_name: "things",
    shells: [:bash, :zsh, :fish]

  zap trash: [
      "~/Library/Caches/things-cli",
    ]

end
