# This file was generated by GoReleaser. DO NOT EDIT.
cask "things" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "615e60ebd9717ab32abbb50e12113fb875bf26f52e61e2e86177cc0c4620d1f1"
      url "https://github.com/ryanlewis/things-cli/releases/download/v#{version}/things_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ryanlewis/things-cli/"
    end
    on_arm do
      sha256 "12d12b294972bb29d5574a730618ed55774ded1c6e8392454a2654a4b0a842da"
      url "https://github.com/ryanlewis/things-cli/releases/download/v#{version}/things_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ryanlewis/things-cli/"
    end
  end

  name "things"
  desc "Manage your Things3 to-dos from the terminal."
  homepage "https://github.com/ryanlewis/things-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "things"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/things"]
    end
  end

  generate_completions_from_executable "things", "completions",
    base_name: "things",
    shell_parameter_format: :arg,
    shells: [:bash, :zsh, :fish]

  zap trash: [
      "~/Library/Caches/things-cli",
    ]

end
